// Code generated by command "run.sh gen_mock_grpc_client". DO NOT EDIT.
package grpcclient

import (
	_ "go.uber.org/mock/mockgen/model"
)

//go:generate mockgen -typed -source=./gen/citilink/store/stock/v1/stock_api_grpc.pb.go -destination=./mock/citilink/store/stock/v1/stock_api_grpc.go StockAPIClient
//go:generate mockgen -typed -source=./gen/citilink/store/store/v1/store_api_grpc.pb.go -destination=./mock/citilink/store/store/v1/store_api_grpc.go StoreAPIClient
