version: '3'

services:
  # добавлен для примера, чтобы команда docker compose up отрабатывала без ошибок. Данный сервис стоит удалить как
  # только появится хотя бы один настоящий
  noop:
    image: rwgrim/docker-noop